config/routes.rb
Rails.application.routes.draw do
  resources :teams do
    member do
      delete 'destroy_user/:user_id', action: :destroy_user, as: :remove_user_from
    end
  end
  get '/home', to: 'teams#home'
  get '/comingsoon', to: 'teams#coming_soon'
  root to: 'teams#home'
end

app/models/team.rb
class Team < ActiveRecord::Base
  has_many :users
  validates :name, presence: true
  validates :project_name, presence: true
  validates :project_description, presence: true
  has_secure_password
  validates :password, length: {minimum: 4}
  accepts_nested_attributes_for :users, allow_destroy: true, reject_if: proc {|a| a["full_name"].blank? and a["email"].blank?}
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :team

  enum role: [:user, :admin]
  after_initialize :set_default_role, :if => :new_record?

  validates :full_name, presence: true
  EMAIL_REGEX = /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  validates :email, presence: true, uniqueness: true
  validates_format_of :email, with: EMAIL_REGEX

  def set_default_role
    self.role = :user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :set_team, only: [:show, :edit, :update, :destroy, :destroy_user]

  def home
  end
  # GET /teams
  # GET /teams.json
  def index
    @teams = Team.all
  end

  def coming_soon
  end

  # GET /teams/1
  # GET /teams/1.json
  def show
  end

  # GET /teams/new
  def new
    @team = Team.new
  end

  # GET /teams/1/edit
  def edit
  end

  # POST /teams
  # POST /teams.json
  def create
    @team = Team.new(team_params)

    respond_to do |format|
      if @team.save
        format.html { redirect_to @team, notice: "Team was successfully created. If there are still team members you would like to add, you may give them the following url so they can add themselves: https://stc.unm.edu/webapp#{team_path(@team)}" }
        format.json { render :show, status: :created, location: @team }
      else
        format.html { render :new }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teams/1
  # PATCH/PUT /teams/1.json
  def update
    respond_to do |format|
      if @team.authenticate(params[:team][:password]) and @team.update(team_params)
        format.html { redirect_to @team, notice: 'Team was successfully updated.' }
        format.json { render :show, status: :ok, location: @team }
      else
        unless @team.authenticate(params[:password])
          @team.errors.add(:password, "did not match our records. Contact the person who created this team and type the password they give you.")
        end
        format.html { render :edit }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teams/1
  # DELETE /teams/1.json
  def destroy
    @team.destroy
    respond_to do |format|
      format.html { redirect_to teams_url, notice: 'Team was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def destroy_user
    user = @team.users.find(params[:user_id])
    user.destroy
    respond_to do |format|
      format.html { redirect_to @team, notice: 'User was successfully removed from this team.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team
      @team = Team.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def team_params
      params.require(:team).permit(:name, :password, :password_confirmation, :project_name, :project_description, users_attributes: [:id, :full_name, :email, :_destroy])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_remove_fields(name, f)
    f.hidden_field(:_destroy) + link_to(name, "#", {onclick: "remove_fields(this); return false;"})
  end
  
  def link_to_add_fields(name, f, association)
    new_object = f.object.class.reflect_on_association(association).klass.new
    fields = f.fields_for(association, new_object, :child_index => "new_#{association}") do |builder|
      render(association.to_s.singularize + "_fields", :f => builder)
    end
    link_to(name, "#", {onclick: "add_fields(this, \"#{association}\", \"#{escape_javascript(fields)}\"); return false;"})
  end
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
%ul      
  %li{class: controller.action_name == "home" ? "current" : ""}
    = link_to 'Home', root_path
  = render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.haml
%li{class: controller.action_name == "index" ? "current" : ""}
  = link_to "Register a Team/User", teams_path
%li
  = link_to "Add first status update", comingsoon_path
%li
  = link_to "Add second status update", comingsoon_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Stc Competition'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Stc Competition'}"}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    #printlogo
      =image_tag("stclogo-horizontal.png")
    #head-wrap
      #head
        #home
          %a{href: "/"}
            Home
        #menu
          = render 'layouts/navigation'
    #content-container
      #banner
      #content-wrap
        = render 'layouts/messages'
        = yield
    #foot-wrap
      #foot
        %h1
          Supporting Technology Transfer and Catalyzing Economic Development at The University of New Mexico
        -##navigation
        -#  %h3.rev-color
        -#    Navigation
        -#  %ul
        -#    %li=link_to "Home", "https://stc.unm.edu"
        -#    %li=link_to "News/Events", "https://stc.unm.edu"
        -#    %li=link_to "Technologies", "https://stc.unm.edu"
        -#    %li=link_to "Inventors", "https://stc.unm.edu"
        -#    %li=link_to "Entrepreneurs", "https://stc.unm.edu"
        -#    %li=link_to "Economic Development", "https://stc.unm.edu"
        -#    %li=link_to "About", "https://stc.unm.edu"
        -##links
        -#  %h3.rev-color
        -#    Quick Links
        -#  %ul
        -#    %li=link_to "Submit a Disclosure", "https://stc.unm.edu"
        -#    %li=link_to "Technology Portfolio", "https://stc.unm.edu"
        -#    %li=link_to "Gap Funding", "https://stc.unm.edu"
        -#    %li=link_to "Board Members Login", "https://stc.unm.edu"
        -#    %li=link_to "CVL Tenant Login", "https://stc.unm.edu"
        -#    %li=link_to "Careers", "https://stc.unm.edu"
        -#    %li=link_to "Semi-Annual Newsletters", "https://stc.unm.edu"
        -##socndet
        -##socnet
        -##contactus